{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "restapi-flask.fullname" . }}
  labels: {{ include "restapi-flask.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: api.localhost.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "restapi-flask.fullname" . }}
            port: 
              number: {{ .Values.app.port | default 5000 }}

{{ end }}