apiVersion: v1
kind: Service
metadata:
  name: {{ include "restapi-flask.fullname" . }}
  labels: {{ include "restapi-flask.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "restapi-flask.fullname" . }}
  ports:
  - port: {{ .Values.app.port | default 5000 }}
