on:
    push:
        branches-ignore:
            - main

jobs:
    deploy:
        runs-on: ubuntu-20.04
        name: deploy-job
        steps:
            - uses: actions/checkout@v3

            - name: install dependencies
              run: |
                pip3 install -r requirements.txt
                pip3 install flake8 pylint

            - name: Run tests
              run: make test