on:
    push:
        branches-ignore:
            - main

jobs:
    test:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: install dependencies
              run: |
                pip3 install -r requirements.txt

            - name: Run tests
              run: make test
    
    deploy:
        needs: test
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Deploy
              run: make heroku
              env:
                HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}


